name: Check PyPI Build
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * 1-5'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install -e .
          python -m pip install build
      
      - name: Check Errors
        run: |
          python -m build
