name: Ensure Sufficient Coverage
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install -e .
          python -m pip install coverage
      - name: Compile Sambvca21
        run: |
          gfortran -o sambvca21.x test/sambvca21.f
      - name: Run Tests
        run: |
          coverage run --source=. --omit=py2sambvca/__init__.py,setup.py,test/* -m unittest discover
      - name: Show Coverage
        run: |
          coverage report -m > temp.txt
          cat temp.txt
          python .github/workflows/coverage_helper.py
          echo "COVERAGE_PERCENT=$(cat temp2.txt)" >> $GITHUB_ENV

      - name: Request Changes via Review
        if: ${{ env.COVERAGE_PERCENT < 95 }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: REQUEST_CHANGES
          body: 'Increase test coverage from ${{ env.COVERAGE_PERCENT }}% to at least 95% before merging.'
  
      - name: Approve PR if Coverage Sufficient
        if: ${{ env.COVERAGE_PERCENT > 94 }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: APPROVE
          body: 'Test coverage meets or exceeds 95% threshold (currently ${{ env.COVERAGE_PERCENT }}%).'
