name: Run Unix Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:      
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Mac OS Python ${{ matrix.python-version }} Subtest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install -e .
          python -m pip install coverage
      - name: Compile Sambvca21
        run: |
          gfortran-10 -o sambvca21.x test/sambvca21.f
      - name: Run Tests
        run: |
          coverage run --source=. --omit=py2sambvca/__init__.py,setup.py,test/* -m unittest discover
      - name: Show Coverage
        run: |
          coverage report -m
